module.exports.ErrorMessage = Object.freeze({
  TASK_NOT_FOUND:"Task not found",
  DATA_AUTHORIZTAION:"Only develper can change the status of the task",
  DATA_SHOULD_BE_ARRAY:"Entered data should be an array",
  CANNOT_ACCESS_DATA: "The requested user cannot access the data",
  PROJECT_NOT_EXIST: "Project not found",
  TASK_DELETED:"Task deleted",
  PROJECT_STATUS:"Project is already completed",
  PROJECT_DELETED: "Project deleted",
  MANAGER_NOT_EXIST: "Manager does not exist",
  NOT_AUTHORISED: "Only admin can create the manager",
  PROJECT_ALREADY_CREATED: "Project is already created",
  INVALID_TOKEN: "Unauthorized user.",
  INVALID_CREDENTIAL: "Invalid credentials.",
  SOMETHING_WRONG: "Something went wrong!",
  ALREADY_EXIST: "Already exists.",
  NO_TOKEN: "Please provide token.",
  EMAIL_NOT_REGISTERED: "Provided email is not registered.",
  NOT_REGISTERED: "Provided email/mobile number is not registered.",
  RESET_PASSWORD_EXPIRED: "Your Token has expired.",
  WRONG_PASSWORD: "Please enter valid password.",
  INVALID_MOBILE: "This mobile number is not valid.",
  EMAIL_EXIST: "This email already exists.",
  NOT_FOUND: "Requested data not found.",
  USER_NOT_FOUND: "This user does not exist.",
  UPDATE_NOT: "Unexpected error during update, please try again.",
  MOBILE_EXIST: "This mobile number already exists.",
  USERNAME_EXIST: "This user name already exists.",
  USER_ID: "A valid User Id is required.",
  BLOCKED_BY_ADMIN: "You are not authorized, please contact Admin.",
  DELETED_BY_ADMIN: "Your account is deleted, please contact Admin.",
  FIELD_REQUIRED: "Fields are required.",
  OLD_PASSWORD: "You have provided an incorrect old password.",
  INCORRECT_JWT: "Invalid JWT token.",
  FORBIDDEN: "There was an error in sending email.",
  PASSMATCH: "Password do not match.",
  EVENT_EXISTS: "Event already added",
  NOT_MATCH: "Password Not Matched.",
  TOKEN_EXISTS: "This Token is already exist",
  ADD_SUCCESS: "Data Added Successfully",
  BLOCK_SUCCESS: "Block successfully",
  ACTIVE_SUCCESS: "Active Successfully",
  UPDATE_SUCCESS: "Data Update Successfully",
  USER_ALREADY_EXIST: "This address already added as user",
  ADMIN_ALREADY_EXIST: "This address already added as Admin",
  DATA_NOT_FOUND: "Data not found",
});

module.exports.SuccessMessage = Object.freeze({
  PROJECT_ADDED: "Project added sucessfully",
  SIGNUP_SUCCESSFULLY: "Thanks, You have successfully signed up.",
  DATA_FOUND: "Requested data found.",
  DEVELOPER_ADD: "Developer added successfully",
  LOGIN_SUCCESS: "Your login is successful.",
  FORGET_SUCCESS: "A password reset link has been sent to your registered ID.",
  RESET_SUCCESS: "Your password was successfully changed.",
  USER_LIST_FETCH: "Successfully fetched user list.",
  AUTHORIZATION: "This User is Authorized.",
  ACCOUNT_CREATION: "Your account has been created successfully.",
  EMAIL_SEND: "Link has been sent to your registered Email successfully.",
  PASSWORD_UPDATE: "Your password has been updated successfully.",
  DATA_SAVED: "Data is saved successfully.",
  DETAIL_GET: "Details have been fetched successfully.",
  DATA_FOUND: "Requested data found.",
  PROFILE_DETAILS: "Your profile details has been updated sucessfully.",
  STATUS_UPDATED: "Your Status has been changed successfully.",
  UPDATE_SUCCESS: "Successfully updated.",
  BLOCK_SUCCESS: "Successfully blocked.",
  UNBLOCK_SUCCESS: "Successfully activated.",
  DELETE_SUCCESS: "Successfully deleted.",
  INVITATION_SUCCESS: "Invitaion sent",
  SESSION_DETAILS: "Session Join user list",
  REMOVE_SUCCESS: "Remove Successfully",
  LIST_EMPTY: "Empty List ",
  PLAYLIST_ADD: "Playlist has been added successfully.",
  SESSION_END: "Session ended without adding playlist.",
  SESSION_START: "Session started successfully.",
  LIMIT_EXCEED: "Limit exceeded.",
  DEVELOPER_ADD: "Developer added successfully",
  CREATE_MANAGER: "Manager created successfully.",
  CREATE_DEVELOPER: "Developer created successfully.",
  TASK_ADD: "Task added Successfully.",
  DEVELOPER_ASSIGNED: "Developer Assigned on task Successfully.",
  TASK_UPDATE:"Task Updated Successfully."
});
